# Generated by Django 5.2.4 on 2025-07-25 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='my_date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
