# Generated by Django 5.2.4 on 2025-07-26 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_alter_location_my_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='loctionRecords',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('my_date', models.DateField(auto_now_add=True)),
                ('loc', models.CharField(max_length=200)),
                ('add_item_list', models.CharField(max_length=200)),
            ],
        ),
    ]
