# Generated by Django 5.2.4 on 2025-07-26 11:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_loctionrecords'),
    ]

    operations = [
        migrations.RenameField(
            model_name='loctionrecords',
            old_name='loc',
            new_name='loc_rec',
        ),
    ]
