# Generated by Django 5.2.4 on 2025-07-26 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_rename_loc_loctionrecords_loc_rec'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loctionrecords',
            name='loc_rec',
            field=models.CharField(default='Not Assigned', max_length=200),
        ),
    ]
