# Generated by Django 5.2.4 on 2025-07-26 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_alter_loctionrecords_add_item_list'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loctionrecords',
            name='loc_rec',
            field=models.CharField(blank=True, default='Not Assigned', max_length=200, null=True),
        ),
    ]
