# Generated by Django 5.2.4 on 2025-07-26 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_alter_loctionrecords_loc_rec'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loctionrecords',
            name='add_item_list',
            field=models.CharField(blank=True, default='Not Soire', max_length=200, null=True),
        ),
    ]
