# Generated by Django 5.2.4 on 2025-07-31 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_file_delete_excelfileupload'),
    ]

    operations = [
        migrations.CreateModel(
            name='MasterData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('my_date', models.DateField(auto_now_add=True)),
                ('ADDL', models.CharField(max_length=100)),
                ('ITEMCODE', models.CharField(max_length=100)),
                ('ITEMNAME', models.CharField(max_length=100)),
                ('SIZE', models.CharField(max_length=100)),
                ('MRP', models.CharField(max_length=100)),
                ('BRANDNAME', models.CharField(max_length=100)),
                ('SECTION', models.CharField(max_length=100)),
                ('BASIC', models.CharField(max_length=100)),
                ('RATE', models.CharField(max_length=100)),
                ('SEASON', models.CharField(max_length=100)),
                ('COLOURS', models.CharField(max_length=100)),
            ],
        ),
    ]
