# Generated by Django 5.2.4 on 2025-07-31 08:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0018_alter_masterfile_file'),
    ]

    operations = [
        migrations.RenameField(
            model_name='masterdata',
            old_name='BASIC',
            new_name='BASICRATE',
        ),
        migrations.RemoveField(
            model_name='masterdata',
            name='RATE',
        ),
    ]
