# Generated by Django 5.2.4 on 2025-08-07 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0019_rename_basic_masterdata_basicrate_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('my_date', models.DateField(auto_now_add=True)),
                ('BRANCHCODE', models.CharField(max_length=200)),
                ('BRANCHNAME', models.CharField(max_length=200)),
                ('COMPANY', models.CharField(max_length=200)),
                ('ARTICLENO', models.CharField(max_length=200)),
                ('ITEMNAME', models.CharField(max_length=200)),
                ('COLOURS', models.CharField(max_length=200)),
                ('BARCODE', models.CharField(max_length=200)),
                ('EANCODE', models.CharField(max_length=200)),
                ('SIZE', models.CharField(max_length=200)),
                ('SECTION', models.CharField(max_length=200)),
                ('BRAND', models.CharField(max_length=200)),
                ('SEASON', models.CharField(max_length=200)),
                ('ITEM_DESC', models.CharField(max_length=200)),
                ('GROUP5_GRP1', models.CharField(max_length=200)),
                ('GENDER', models.CharField(max_length=200)),
                ('GST', models.CharField(max_length=200)),
                ('CLOSINGSTOCK', models.CharField(max_length=200)),
                ('COST', models.CharField(max_length=200)),
                ('MRP', models.CharField(max_length=200)),
                ('CLOSINGVALUECOST', models.CharField(max_length=200)),
                ('CLOSINGVALUEMRP', models.CharField(max_length=200)),
                ('GODOWNNAME', models.CharField(max_length=200)),
                ('ITEMNAME_SHADESHORTNAME_PACKGROUPNAME', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='stockFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='stockfile')),
            ],
        ),
    ]
