# Generated by Django 5.2.4 on 2025-08-13 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0020_stockdata_stockfile'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockdata',
            name='SCANNINGDATA',
            field=models.CharField(default='Short', max_length=255),
        ),
    ]
