# Generated by Django 5.2.4 on 2025-08-17 04:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0023_excessscanning'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stockdata',
            name='SCANNINGDATA',
        ),
    ]
