# Generated by Django 5.2.4 on 2025-08-17 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0024_remove_stockdata_scanningdata'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockdata',
            name='scanningDATA',
            field=models.CharField(default='Short', max_length=255),
        ),
    ]
