# Generated by Django 5.2.4 on 2025-08-18 01:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0025_stockdata_scanningdata'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stockdata',
            name='scanningDATA',
        ),
    ]
