# Generated by Django 5.2.4 on 2025-08-18 01:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0026_remove_stockdata_scanningdata'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockdata',
            name='ScanningData',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scanningData', to='home.stockdata'),
        ),
    ]
