# Generated by Django 5.2.4 on 2025-08-18 02:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0027_stockdata_scanningdata'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stockdata',
            name='ScanningData',
        ),
    ]
