# Generated by Django 5.2.4 on 2025-08-18 05:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0029_stockdata_scanningdata'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stockdata',
            name='scanningdata',
        ),
    ]
