# Generated by Django 5.2.4 on 2025-08-23 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0030_remove_stockdata_scanningdata'),
    ]

    operations = [
        migrations.CreateModel(
            name='scanningFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='scanningFile')),
            ],
        ),
    ]
