# Generated by Django 5.2.4 on 2025-07-18 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='YourModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=100)),
                ('addl', models.CharField(max_length=100)),
                ('itemcode', models.CharField(max_length=100)),
                ('itemname', models.CharField(max_length=100)),
                ('size', models.CharField(max_length=50)),
                ('qty', models.IntegerField()),
            ],
        ),
    ]
