# Generated by Django 5.2.4 on 2025-07-24 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_teacher'),
    ]

    operations = [
        migrations.CreateModel(
            name='dataEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('my_date', models.DateField()),
                ('my_text', models.CharField(max_length=200)),
            ],
        ),
    ]
