# Generated by Django 5.2.4 on 2025-07-31 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0016_masterdata'),
    ]

    operations = [
        migrations.CreateModel(
            name='masterFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='files')),
            ],
        ),
    ]
