# Generated by Django 5.2.4 on 2025-08-16 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0022_excessrecordscanning'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExcessScanning',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('my_date', models.DateField(auto_now_add=True)),
                ('loc_rec', models.CharField(blank=True, default='Not Assigned', max_length=200, null=True)),
                ('add_item_list', models.CharField(blank=True, default='Not Soire', max_length=200, null=True)),
            ],
        ),
    ]
